"""empty message

Revision ID: 11f168914e56
Revises: 9df5e65285ad
Create Date: 2025-06-09 14:26:17.079371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11f168914e56'
down_revision = '9df5e65285ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_kurs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('kurs_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kurs_id'], ['kurs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))
        batch_op.drop_constraint('user_predment_id_fkey', type_='foreignkey')
        batch_op.drop_column('predment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('predment_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('user_predment_id_fkey', 'predment', ['predment_id'], ['id'])
        batch_op.drop_column('phone')

    op.drop_table('user_kurs')
    # ### end Alembic commands ###
