"""empty message

Revision ID: 1f52d61e0e97
Revises: 945d0d1c9792
Create Date: 2025-05-30 10:51:29.541623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f52d61e0e97'
down_revision = '945d0d1c9792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_kurs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('predment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['predment_id'], ['predment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('user_pred')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_pred',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('predment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['predment_id'], ['predment.id'], name='user_kurs_predment_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_kurs_user_id_fkey')
    )
    op.drop_table('user_kurs')
    # ### end Alembic commands ###
