"""empty message

Revision ID: 23d84655f72d
Revises: 69dd0f9c3527
Create Date: 2025-05-21 16:22:24.427455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d84655f72d'
down_revision = '69dd0f9c3527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kurs', schema=None) as batch_op:
        batch_op.drop_constraint('kurs_teacher_id_fkey', type_='foreignkey')
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kurs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('kurs_teacher_id_fkey', 'teacher', ['teacher_id'], ['id'])

    # ### end Alembic commands ###
