"""empty message

Revision ID: 287fc93e4cef
Revises: 7a8f39d1cd5e
Create Date: 2025-05-19 15:51:13.798715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '287fc93e4cef'
down_revision = '7a8f39d1cd5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_kurss',
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('kurs_id', sa.Integer(), nullable=True),
    sa.Column('predment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kurs_id'], ['kurs.id'], ),
    sa.ForeignKeyConstraint(['predment_id'], ['predment.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_kurss')
    # ### end Alembic commands ###
