"""empty message

Revision ID: 73a5067a663b
Revises: 5e82541d668c
Create Date: 2025-05-10 21:07:20.287685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a5067a663b'
down_revision = '5e82541d668c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(), nullable=True))
        batch_op.drop_column('study')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('study', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
