"""empty message

Revision ID: 769dae3a33a9
Revises: 46b08bc968f4
Create Date: 2025-05-17 17:56:24.414003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769dae3a33a9'
down_revision = '46b08bc968f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('predment_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['predment_id'], ['predment.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kurs')
    op.drop_table('predment')
    # ### end Alembic commands ###
