"""empty message

Revision ID: 8cec2ac2f590
Revises: 1f52d61e0e97
Create Date: 2025-05-30 11:16:33.965263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cec2ac2f590'
down_revision = '1f52d61e0e97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_pred',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('predment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['predment_id'], ['predment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('user_kurs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_kurs',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('predment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['predment_id'], ['predment.id'], name='user_kurs_predment_id_fkey1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_kurs_user_id_fkey1')
    )
    op.drop_table('user_pred')
    # ### end Alembic commands ###
