"""empty message

Revision ID: 945d0d1c9792
Revises: eba1c0663888
Create Date: 2025-05-30 10:48:32.692035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945d0d1c9792'
down_revision = 'eba1c0663888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_kurs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('predment_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('user_kurs_kurs_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'predment', ['predment_id'], ['id'])
        batch_op.drop_column('kurs_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_kurs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kurs_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_kurs_kurs_id_fkey', 'kurs', ['kurs_id'], ['id'])
        batch_op.drop_column('predment_id')

    # ### end Alembic commands ###
