"""empty message

Revision ID: 9df5e65285ad
Revises: d3798f8fba55
Create Date: 2025-06-01 14:18:45.038911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df5e65285ad'
down_revision = 'd3798f8fba55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kurs_predment')
    op.drop_table('user_pred')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('predment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'predment', ['predment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('predment_id')

    op.create_table('user_pred',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('predment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['predment_id'], ['predment.id'], name='user_pred_predment_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_pred_user_id_fkey')
    )
    op.create_table('kurs_predment',
    sa.Column('kurs_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('predment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['kurs_id'], ['kurs.id'], name='kurs_predment_kurs_id_fkey'),
    sa.ForeignKeyConstraint(['predment_id'], ['predment.id'], name='kurs_predment_predment_id_fkey')
    )
    # ### end Alembic commands ###
