"""empty message

Revision ID: a10da9656af0
Revises: 73a5067a663b
Create Date: 2025-05-10 21:34:33.736564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a10da9656af0'
down_revision = '73a5067a663b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('year')
        batch_op.drop_column('pol')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pol', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
