"""empty message

Revision ID: a61e010e3a7a
Revises: 769dae3a33a9
Create Date: 2025-05-18 18:19:25.532482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a61e010e3a7a'
down_revision = '769dae3a33a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kurs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kurs', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
