"""empty message

Revision ID: b3778b833847
Revises: 287fc93e4cef
Create Date: 2025-05-21 13:55:06.528797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3778b833847'
down_revision = '287fc93e4cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_kurs',
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('kurs_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kurs_id'], ['kurs.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], )
    )
    op.drop_table('user_kurss')
    with op.batch_alter_table('kurs', schema=None) as batch_op:
        batch_op.drop_constraint('kurs_teacher_id_fkey', type_='foreignkey')
        batch_op.drop_column('teacher_id')
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kurs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('kurs_teacher_id_fkey', 'teacher', ['teacher_id'], ['id'])

    op.create_table('user_kurss',
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('kurs_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('predment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['kurs_id'], ['kurs.id'], name='user_kurss_kurs_id_fkey'),
    sa.ForeignKeyConstraint(['predment_id'], ['predment.id'], name='user_kurss_predment_id_fkey'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], name='user_kurss_teacher_id_fkey')
    )
    op.drop_table('user_kurs')
    # ### end Alembic commands ###
