"""empty message

Revision ID: d3798f8fba55
Revises: 8cec2ac2f590
Create Date: 2025-05-31 09:52:28.675435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3798f8fba55'
down_revision = '8cec2ac2f590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kurs_predment',
    sa.Column('kurs_id', sa.Integer(), nullable=True),
    sa.Column('predment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kurs_id'], ['kurs.id'], ),
    sa.ForeignKeyConstraint(['predment_id'], ['predment.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kurs_predment')
    # ### end Alembic commands ###
