"""empty message

Revision ID: eba1c0663888
Revises: ffc443fe8741
Create Date: 2025-05-29 18:08:47.217066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eba1c0663888'
down_revision = 'ffc443fe8741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.String(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('year')

    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_column('year')

    # ### end Alembic commands ###
